apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-application
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      run: express-application
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: express-application
    spec:
      containers:
        - image: tsakar/express-app:latest
          name: express-application
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: database
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database
                  key: MYSQL_PASSWORD
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
