apiVersion: v1
kind: Service
metadata:
  labels:
    run: express-application
  name: express-application
  namespace: development
spec:
  externalTrafficPolicy: Cluster
  ports:
    - port: 9000
      targetPort: 9000
  selector:
    run: express-application
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
